### ISSUE TITLE
USBMSC Identifier (non-unique)

### ISSUE THREAD

**Issue by estevanpedro** [leandro1988n/ASUS-X751LJ-Hackintosh#1]
Leandro, tentei usar suas configurações, mas tomei esse erro, você tem essa solução? Tenho o mesmo Asus que o seu.

Leandro, I tried to use your settings, but I took this error, do you have this solution? I have the same Asus as yours.

`USBMSC Identifier (non-unique)`

**Comment by leandro1988n** [comment]
Teste o ultimo release eu uso SSD, então havia um patch no config.plist para habilitar o TRIM, eu desabilitei o patch.

Test the latest release I use SSD, so there was a patch in config.plist to enable TRIM, I disabled the patch.

**Comment by estevanpedro** [comment]
Oi Leandro,

Estou faz 2 semanas, hoje virei a noite tentando arrumar e nada. Como eu testo o último release? O que seria isso?


Agradeço tremendamente, posso até pagar se fazer rodar.

Abraços
Estevan Pedro

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by estevanpedro** [comment]
High Sierra 10.13.4

**Comment by leandro1988n** [comment]
Nunca consegui fazer o High Sierra dar boot, a configuração que eu disponibilizo e para o macOS Mojave 10.14
